---
title: "Procesos Estocásticos y Series Temporales"
subtitle: "Entregable Práctica 1"
author: "Francisco Javier Mercader Martínez"
output: 
  pdf_document:
    latex_engine: xelatex
geometry: margin=1.5cm, a4paper
header-includes:
- \renewcommand{\and}{\\}
- \usepackage{fvextra}
- \usepackage{hyperref}
- \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines, commandchars=\\\{\}}
---

# Problema 1

Apartado (a)

```{r, message=FALSE}
library(markovchain)
set.seed(1234)

estados <- as.character(1:6) # Definimos los estados
P <- rbind(c(1/3, 2/3, 0, 0, 0, 0),
           c(1/2, 1/2, 0, 0, 0, 0),
           c(1/5, 0, 0, 3/5, 1/5, 0),
           c(0, 1/5, 2/5, 0, 0, 2/5),
           c(0, 0, 0, 0, 1/3, 2/3),
           c(0, 0, 0, 0, 1/4, 3/4))

mc <- new("markovchain", states = estados, transitionMatrix = P)

plot(mc)

summary(mc)
```

Apartado (b)

```{r}
meanAbsorptionTime(mc)
```

Apartado (c)

```{r}
X0 <- "3"
conditionalDistribution(mc, X0)
```

Apartado (d)

```{r}
X0 <- "4"
conditionalDistribution(mc, X0)
```

# Problema 2

Apartado (a)

```{r}
estados <- c("A", "B", "C", "Nada") # Invierte en uno de los tres o en ninguno

P <- rbind(c(0.5, 0.2, 0.1, 0.2),
           c(0.25, 0.5, 0.05, 0.2),
           c(0.5, 0, 0.4, 0.1),
           c(0, 0, 0, 1))

mc.inversion <- new("markovchain", states <- estados, transitionMatrix = P, name = "Inversiones")

set.seed(1234)
plot(mc.inversion)
```


Apartado (b)

```{r, message=FALSE}
library(expm)
P %^% 1
P %^% 4
P %^% 8
```

Apartado (c)

```{r}

```

Apartado (d)

```{r}
inversores_totales <- 400 + 350 + 250 # clientes que han invertido este año en algún producto
distribucion_inicial <- c(400, 350, 250, 6000 - inversores_totales) / 6000

# Dentro de 8 años
distribucion_8_años <- distribucion_inicial %*% (P %^% 8)
inversores_8_años <- (distribucion_8_años[1] + distribucion_8_años[2] + distribucion_8_años[3]) * 6000
cat("Clientes que inviertan en los próximos 8 años:", round(inversores_8_años))
```

# Problema 3

Apartado (a)

```{r, message=FALSE}

# Definición de los estados
estados <- c("A", "B", "C", "D", "E", "F", "G")

# Definimos la matriz de transición
P <- rbind(c(0, 1/2, 1/2, 0, 0, 0, 0),
           c(0, 0, 0, 1/3, 0, 1/3, 1/3),
           c(1, 0, 0, 0, 0, 0, 0),
           c(0, 1, 0, 0, 0, 0, 0),
           c(0, 0, 1/3, 1/3, 0, 1/3, 0),
           c(0, 1/2, 1/2, 0, 0, 0, 0),
           c(0, 0, 0, 1, 0, 0, 0))

mc.pageRank <- new("markovchain", states = estados,
                   transitionMatrix = P, name = "PageRak")

is.irreducible(mc.pageRank)
```
Apartado (b)

```{r}
d <- 0.7
n <- 7
M <- d*P + (1-d)*(1/n)*matrix(1, n, n)
M
mc.pageRank <- new("markovchain", states = estados,
                   transitionMatrix = M, name = "PageRak")
is.irreducible(mc.pageRank)
period(mc.pageRank)
```

Apartado (c)

```{r}
steadyStates(mc.pageRank)
```

# Problema 4

```{r, message=FALSE}

```

