---
title: "Visualización de Datos"
subtitle: "**Pandas:** Manejo de *arrays* multidimensionales a través *DataFrames* de la librería *Pandas*"
author: "Francisco Javier Mercader Martínez"
format:
    pdf:
        documentclass: article
        highlight-style: tango
        header-includes: |
            \usepackage{multicol}
            \usepackage{enumitem}
            \renewcommand{\and}{\\}
            \usepackage{fvextra}
            \usepackage{hyperref}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines, commandchars=\\\{\}}
linestrectch: 1.5
fontisize: 10
papersize: a4
geometry: margin=1.5cm
---

# Ejercicios

**Ejercicio 1.** Crea un Data con la siguiente información:

| Nombre | Grupo Sanguíneo | Edad | Peso | Ritmo Cardiaco | Presión Sistólica | Presión Diastólica |
|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
| Eduardo | B+ | 40 | 70 | 70 | 129 | \- |
| Ana | O+ | 35 | 69 | 60 | 133 | 86 |
| Alejandro | AB+ | 37 | 74 | 68 | 125 | 82 |
| Álvaro | O+ | 24 | 70 | 50 | 110 | 70 |
| Aitana | A+ | 48 | 72 | 68 | \- | 82 |
| María | A+ | 53 | 67 | 87 | 130 | 84 |
| Sofia | B- | 67 | 65 | 110 | 155 | 100 |
| Antonio | A+ | 25 | 74 | \- | 126 | 89 |
| Fernando | AB+ | 38 | 75 | 77 | 131 | 90 |
| Laura | O+ | 21 | 70 | 69 | 127 | 87 |

```{python}
import pandas as pd
import numpy as np

data = {
    "Nombre": ["Eduardo", "Ana", "Alejandro", "Álvaro", "Aitana", "María", "Sofia", "Antonio", "Fernando", "Laura"],
    "Grupo Sanguíneo": ["B+", "O+", "AB+", "O+", "A+", "A+", "B-", "A+", "AB+", "O+"],
    "Edad": [40, 35, 37, 24, 48, 53, 67, 25, 38, 21],
    "Peso": [70, 69, 74, 70, 72, 67, 65, 74, 75, 70],
    "Ritmo Cardiaco": [70, 60, 68, 50, 68, 87, 110, None, 77, 69],
    "Presión Sistólica": [129, 133, 125, 110, None, 130, 155, 126, 131, 127],
    "Presión Diastólica": [None, 86, 82, 70, 82, 84, 100, 89, 90, 87]
}

df = pd.DataFrame(data)
df['Altura'] = np.random.uniform(1.55, 1.81, size=len(df)).round(2)
print(df)
```

**Ejercicio 2.** Crea una nueva columna en el DataFrame anterior donde aparezca el cálculo del Indice de Masa Corporal (IMC) que se calcula de la siguiente forma:

$$
IMC=\frac{\text{peso}}{\text{altura}^2}
$$

```{python}
df["IMC"] = (df['Peso'] / (df['Altura']**2)).round(2)
print(df)
```

**Actividad 3.** Convierte la columna Grupo Sanguíneo de 2 formas distintas (sin eliminar la columna original)

-   Usando un Label Encoding

    ```{python}
    from sklearn.preprocessing import LabelEncoder
    label_encoder = LabelEncoder()
    # Grupo Sanguíneo Label Encoding (GS_LE)
    df['GS_LE'] = label_encoder.fit_transform(df['Grupo Sanguíneo'])
    print(df)
    ```

-   Usando un esquema de One Hot Encoding

    ```{python}
    from sklearn.preprocessing import OneHotEncoder
    ohe_encoder = OneHotEncoder()
    ohe_df = pd.DataFrame(ohe_encoder.fit_transform(df[["Grupo Sanguíneo"]]).toarray())
    df_merged = pd.concat([df, ohe_df], axis=1)
    print(df_merged)
    ```

**Ejercicio 4.** Elimina la columna original de Grupo Sanguíneo.

```{python}
print(df.drop('Grupo Sanguíneo', axis=1))
```

**Ejercicio 5.** Une el DataFrame anterior con el siguiente

|  Nombre  |  Cuidad   | Nivel de Estudios     | Azúcar | Colesterol |
|:--------:|:---------:|:----------------------|:------:|:----------:|
| Eduardo  | Valencia  | Primaria              |   80   |    156     |
|   Ana    |  Murcia   | Primaria              |   82   |    167     |
|  Manuel  |  Madrid   | Primaria              |  114   |    204     |
|  Aitana  | Barcelona | Primaria              |   94   |    226     |
|  María   |  Sevilla  | Universidad           |  130   |    167     |
| Antonio  |  Madrid   | Formación Profesional |   83   |    190     |
| Fernando | Barcelona | Secundaria            |   82   |    199     |
|  Angela  |  Murcia   | Secundaria            |  103   |    192     |

```{python}
# Datos del segundo DataFrame
data2 = {
    "Nombre": ["Eduardo", "Ana", "Manuel", "Aitana", "María", "Antonio", "Fernando", "Angela"],
    "Cuidad": ["Valencia", "Murcia", "Madrid", "Barcelona", "Sevilla", "Madrid", "Barcelona", "Murcia"],
    "Nivel de Estudios": ["Primaria", "Primaria", "Primaria", "Primaria", "Universidad", "Formación Profesional", "Secundaria", "Secundaria"],
    "Azúcar": [80, 82, 114, 94, 130, 83, 82, 103],
    "Colesterol": [156, 167, 204, 226, 167, 190, 199, 192]
}

df2 = pd.DataFrame(data2)

# Unir los DataFrames
df_merged = pd.merge(df, df2, on="Nombre", how="left")
print(df_merged)
```

**Actividad 6.** Calcula las medias y las deviaciones típicas de todos los valores números del DataFrame