---
title: "Seminario de Series Temporales"
author: "Francisco Javier Mercader Martínez"
date: "08/10/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, options(digits = 4))

# Definir paquetes requeridos
paquetes_requeridos <- c("ggplot2", "dplyr", "forecast", "tseries", "imputeTS", "caret")

# Función para verificar si los paquetes están instalados
instalar_paquete <- function(paquete) {
  if (!require(paquete, character.only = TRUE)) {
    message(paste("Instalado el paquete", paquete))
    install.packages(paquete, dependencies = TRUE)
    library(paquete, character.only = TRUE)
  }
}

# Instalar paquetes necesarios
invisible(sapply(paquetes_requeridos, instalar_paquete))
```

```{r}
print(Nile)
length(Nile)
head(Nile, n = 10)
tail(Nile, n = 12)
```

```{r, warning=FALSE}
summary(AirPassengers)
library(ggfortify)
autoplot(AirPassengers, ts.colour = "red", ts.linetype = "dashed")
autoplot(co2, ts.colour = "red", ts.linetype = "dashed")
autoplot(co2, ts.colour = "red", ts.linetype = "dashed") + theme_minimal()
summary(co2)
```

```{r}
autoplot(AirPassengers)
start(AirPassengers)
end(AirPassengers)
deltat(AirPassengers)
frequency(AirPassengers)
time(AirPassengers)
cycle(AirPassengers)
```
```{r}
time_index <- time(AirPassengers)

AirPassengers[which(floor(time_index) == 1956)] <- NA

plot(AirPassengers)

mean(AirPassengers)

mean(AirPassengers, na.rm = TRUE)

AirPassengers[85:96] <- mean(AirPassengers, na.rm = TRUE)

plot(AirPassengers)

rm(AirPassengers)
points(AirPassengers, type = "l", col = 2, lty = 3)
```

```{r}
data_vector <- c(10, 6, 11, 8, 10, 3, 6, 9)
data_vector
time_series <- ts(data_vector)
plot(time_series)
time_series <- ts(data_vector, start = 2001, frequency = 1)
plot(time_series)
is.ts(data_vector)
is.ts(time_series)

```

```{r}
x <- ts(rnorm(100), frequency = 12)
dx = diff(x, lag=4)
ts.plot(dx)
```

```{r}
white_noise <- arima.sim(model = list(order = c(0,0,0)), n = 100)
ts.plot(white_noise)
```

```{r}
white_noise_2 <- arima.sim(model = list(order = c(0, 0, 0)), n = 100, mean = 100, sd = 10)
ts.plot(white_noise_2)

y <- arima.sim(model = list(order = c(0,0,0)), n = 100)
arima(y, order = c(0,0,0))
arima(y, order = c(0,0,0))
mean(y)
var(y)
```

