AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Completa Practica 4 (Red + ALB + ECS Cluster + ASG)

Parameters:
  KeyName:
    Description: Nombre del par de claves (.pem).
    Type: AWS::EC2::KeyPair::KeyName
  LabInstanceProfileName:
    Description: Nombre del Perfil de Instancia IAM (En Academy es LabInstanceProfile).
    Type: String
    Default: LabInstanceProfile

Resources:
  # --- 1. RED ---
  Prac4VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: [{Key: Name, Value: prac4-vpc}]

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Prac4VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Prac4VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Prac4VPC
      CidrBlock: 192.168.1.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags: [{Key: Name, Value: prac4-public-subnet-1}]

  Subnet1Route:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Prac4VPC
      CidrBlock: 192.168.2.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: true
      Tags: [{Key: Name, Value: prac4-public-subnet-2}]

  Subnet2Route:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # --- 2. SEGURIDAD ---
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite HTTP al balanceador
      VpcId: !Ref Prac4VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ECSHostSecurityGroup: # Seguridad para las instancias del cluster y DockerInstance
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Seguridad para hosts ECS y Docker
      VpcId: !Ref Prac4VPC
      SecurityGroupIngress:
        - IpProtocol: tcp # SSH
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp # Trafico desde el ALB
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  # --- 3. ECS CLUSTER & WORKERS ---
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: icap-cluster

  # Launch Configuration para las instancias del cluster (Workers)
  ECSLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id}}'
      InstanceType: t3.micro
      IamInstanceProfile: !Ref LabInstanceProfileName
      KeyName: !Ref KeyName
      SecurityGroups: [!Ref ECSHostSecurityGroup]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config

  # Grupo de Autoescalado (Crea las 4 instancias requeridas)
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: [!Ref PublicSubnet1, !Ref PublicSubnet2]
      LaunchConfigurationName: !Ref ECSLaunchConfiguration
      MinSize: '4'
      MaxSize: '4'
      DesiredCapacity: '4'
      Tags:
        - Key: Name
          Value: ECS-Worker-Node
          PropagateAtLaunch: true

  # --- 4. BALANCEADOR DE CARGA (ALB) ---
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: icap-alb
      Subnets: [!Ref PublicSubnet1, !Ref PublicSubnet2]
      SecurityGroups: [!Ref ALBSecurityGroup]
      Scheme: internet-facing

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: icap-tg
      VpcId: !Ref Prac4VPC
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: '200'

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # --- 5. REPOSITORIO ECR ---
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: icap-practica4
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Expire untagged","selection":{"tagStatus":"untagged","countType":"sinceImagePushed","countUnit":"days","countNumber":1},"action":{"type":"expire"}}]}

  # --- 6. INSTANCIA DE GESTIÓN (BUILDER) ---
  DockerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref LabInstanceProfileName
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds: [!Ref ECSHostSecurityGroup]
      Tags: [{Key: Name, Value: DockerInstance}]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          
          mkdir -p /home/ec2-user/icap-practica4
          cd /home/ec2-user/icap-practica4
          
          # Descarga de archivos desde GitHub
          wget https://raw.githubusercontent.com/franjavi-upct-es/cid-upct/refs/heads/main/Pr%C3%A1cticas/3%C2%BA%20Curso/1%C2%BA%20Cuatrimestre/ICAP/Practica_4/app.py
          wget https://raw.githubusercontent.com/franjavi-upct-es/cid-upct/refs/heads/main/Pr%C3%A1cticas/3%C2%BA%20Curso/1%C2%BA%20Cuatrimestre/ICAP/Practica_4/Dockerfile
          wget https://raw.githubusercontent.com/franjavi-upct-es/cid-upct/refs/heads/main/Pr%C3%A1cticas/3%C2%BA%20Curso/1%C2%BA%20Cuatrimestre/ICAP/Practica_4/requirements.txt
          
          chown -R ec2-user:ec2-user /home/ec2-user/icap-practica4
          
          # 3. BUILD & PUSH AUTOMÁTICO
          # Usamos las variables de CloudFormation directamente aquí
          REGION="us-east-1"
          REPO_URI="${ECRRepository.RepositoryUri}"
          CLUSTER="${ECSCluster}"
          TG_ARN="${TargetGroup}"
          
          # Construir
          docker build -t icap-practica4 .
          
          # Subir
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URI
          docker tag icap-practica4:latest $REPO_URI:latest
          docker push $REPO_URI:latest
          
          # 4. DESPLIEGUE EN ECS (CLI dentro de la instancia)
          # Obtenemos Account ID dinámicamente
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          
          # Registrar Tarea (Modo HOST para metadatos)
          aws ecs register-task-definition \
            --family icap-task \
            --network-mode host \
            --requires-compatibilities EC2 \
            --cpu 256 \
            --memory 256 \
            --execution-role-arn "arn:aws:iam::$ACCOUNT_ID:role/LabRole" \
            --container-definitions "[{\"name\":\"icap-container\",\"image\":\"$REPO_URI:latest\",\"cpu\":256,\"memory\":256,\"portMappings\":[{\"containerPort\":5000,\"hostPort\":5000,\"protocol\":\"tcp\"}],\"essential\":true}]" \
            --region $REGION

          # Crear Servicio
          aws ecs create-service \
            --cluster $CLUSTER \
            --service-name icap-service \
            --task-definition icap-task \
            --desired-count 4 \
            --launch-type EC2 \
            --load-balancers "targetGroupArn=$TG_ARN,containerName=icap-container,containerPort=5000" \
            --region $REGION

Outputs:
  ALBDNS:
    Description: URL de la aplicación (Espera unos minutos tras la creación)
    Value: !GetAtt LoadBalancer.DNSName