---
title: "Simulacro 1 Examen PEST"
filters:
  - tikz
format:
  html: {}
tikz:
  cache: false
---

# Problema 1

Sea $(X_t)_{t=0,1,2,...}$ un proceso en tiempo dicreto tal que:

$$
\begin{array}{c}
    \mathbb{E}[X_t]=2\;\forall t\\
    \mathrm{Cov}(X_s,X_t)=0.5^{|t-s|}\;\forall s,t
\end{array}
$$

Definamos, para $t\ge 1$, $$Y_t=X_t-\dfrac{1}{2}X_{t-1}.$$

a) Calcula $\mathbb{E}[Y_t]$ 

   $\mathbb{E}[Y_t]=\mathbb{E}\left[ X_t-\dfrac{1}{2}X_{t-1} \right]=\mathbb{E}[X_t]-\dfrac{1}{2}\mathbb{E}[X_{t-1}]=2-2\cdot \dfrac{1}{2}=1\;\forall t$

b) Calcula $\mathrm{Cov}(Y_s,Y_t)$ para $s,t\ge 1$.

   $\begin{aligned}\mathrm{Cov}(Y_s,Y_t)&=\mathrm{Cov}\left( X_s-\dfrac{1}{2}X_{s-1},X_t-\dfrac{1}{2}X_{t-1} \right)\\&=\mathrm{Cov}\left( X_s,X_t \right)-\mathrm{Cov}\left( X_s,\dfrac{1}{2}X_{t-1} \right)-\mathrm{Cov}\left( \dfrac{1}{2}X_{s-1},X_{t} \right) +\mathrm{Cov}\left( \dfrac{1}{2}X_{s-1},\dfrac{1}{2}X_{t-1} \right)\\&= 0.5^{|t-s|}-0.5^{\left|\frac{1}{2} (t-1)-s\right|}-0.5^{\left|t-\frac{1}{2}(s-1) \right|}+ 0.5^{\left| \frac{1}{2}(t-1-s+1) \right| } \\&= 0.5^{\frac{3}{2} \left| (t-s) \right| } -0.5^{\left| \frac{1}{2} (t-1)-s \right| }-0.5^{\left| t-\frac{1}{2} (s-1) \right| }\\\end{aligned}$

c) Justifica si $(Y_t)$ es débilmente estacionario.

   - Media constante para todo $t$.
   - La covarianza depende del salto entre los instantes de tiempo

   Por lo tanto, no es débilmente estacionario.

# Problema 2

Considera la cadena de Markov homogénea con espacio de estados  $S=\{1,2,3,4,5,6\}$ y matriz de transición:

$$
P=\begin{pmatrix} 
0.7 & 0.3 & 0 & 0 & 0 & 0\\
0.4 & 0.6 & 0 & 0 & 0 & 0\\
0.2 & 0 & 0 & 0.5 & 0.3 & 0\\
0 & 0.1 & 0.4 & 0 & 0 & 0.5\\
0 & 0 & 0 & 0 & 0.6 & 0.4\\
0 & 0 & 0 & 0 & 0.2 & 0.8\\
\end{pmatrix}
$$

a) Encuentra las **clases comunicantes** e indica cuáles son **cerradas**. Clasifica los estados (transitorios/recurrentes) e indica el periodo de las clases cerradas.

```{.tikz}
\begin{tikzpicture}[
	state/.style={circle,draw,font=\sffamily\large\bfseries},
	>=stealth,
	scale=2
	]
	\node[state] (1) at (0,0) {1};
	\node[state] (2) at (0,-2) {2};
	\node[state] (3) at (2,0) {3};
	\node[state] (4) at (2,-2) {4};
	\node[state] (5) at (4,0) {5};
	\node[state] (6) at (4,-2) {6};
	
	\draw[->] (1) to[in=225-90, out=135-90, looseness=10] node[midway, above] {$0.7$} (1);
	\draw[->] (2) to[in=225+90, out=135+90, looseness=10] node[midway, below] {$0.7$} (2);
	\draw[->] (5) to[in=315-180, out=225-180, looseness=10] node[midway, above] {$0.6$} (5);
	\draw[->] (6) to[in=315, out=225, looseness=10] node[midway, below] {$0.8$} (6);
	\draw[->] (2) to[bend right=20] node[midway, right] {$0.4$} (1);
	\draw[->] (1) to[bend right=20] node[midway, left] {$0.3$} (2);
	\draw[->] (3) -- node[midway,above] {$0.2$} (1);
	\draw[->] (4) -- node[midway,below] {$0.1$} (2);
	\draw[->] (3) -- node[midway,above] {$0.3$} (5);
	\draw[->] (4) -- node[midway,below] {$0.5$} (6);
	\draw[->] (4) to[bend right=20] node[midway, right] {$0.5$} (3);
	\draw[->] (3) to[bend right=20] node[midway, left] {$0.4$} (4);
	\draw[->] (6) to[bend right=20] node[midway, right] {$0.4$} (5);
	\draw[->] (5) to[bend right=20] node[midway, left] {$0.2$} (6);
\end{tikzpicture}
```

   Clases irreducibles $$C_1=\{1,2\},C_2=\{3,4\},C_3=\{5,6\}$$ 

   - Los estados $3,4$ son transitorios.
   - Los estados 1,2,5,6 son recurrentes.

   No hay ningún estado absorvente.

   Las clases cerradas tienen periodo 2 y 3, ya que, por ejemplo:
   
   - Desde  $1\to 1$, $1\to 2\to 1$.

   Lo mismo pasa con los estados 2, 5, 6

b) Sea $A=\{1,2\}$. Calcula la probabilidad de que, empezando en el estado 3, la cadena **alcance algún estado de $A$** (en algún instante).

```{.tikz}
\begin{tikzpicture}[
	state/.style={circle,draw,font=\sffamily\large\bfseries},
	>=stealth,
	scale=2
	]
	\node[state] (1) at (0,-1) {A};
	\node[state] (3) at (2,0) {3};
	\node[state] (4) at (2,-2) {4};
	\node[state] (5) at (4,0) {5};
	\node[state] (6) at (4,-2) {6};
	
	\draw[->] (1) to[in=225, out=135, looseness=10] node[midway, left] {$1$} (1);
	\draw[->] (5) to[in=315-180, out=225-180, looseness=10] node[midway, above] {$0.6$} (5);
	\draw[->] (6) to[in=315, out=225, looseness=10] node[midway, below] {$0.8$} (6);
	\draw[->] (3) -- node[midway,above] {$0.2$} (1);
	\draw[->] (4) -- node[midway,below] {$0.1$} (1);
	\draw[->] (3) -- node[midway,above] {$0.3$} (5);
	\draw[->] (4) -- node[midway,below] {$0.5$} (6);
	\draw[->] (4) to[bend right=20] node[midway, right] {$0.5$} (3);
	\draw[->] (3) to[bend right=20] node[midway, left] {$0.4$} (4);
	\draw[->] (6) to[bend right=20] node[midway, right] {$0.4$} (5);
	\draw[->] (5) to[bend right=20] node[midway, left] {$0.2$} (6);
\end{tikzpicture}
```

   Sean $$r_{3,A}=\mathbb{P}(\text{Visitar $A$ para  $n\ge 1$}|X_0=3)\text{ y }r_{4,A}=\mathbb{P}(\text{Visitar $A$ para  $n\ge 1$}|X_0=4)$$

   Desde 3 podemos saltar directamente a $A$, a $4$ y a $5$. Tenemos que:
   
   $$
   \begin{aligned}
       r_{3,A}&= p_{3,A}\cdot 1+p_{3,4}\cdot r_{4,A}+p_{3,5}\cdot \cancelto{0}{r_{5,A}}  \\
       &= 0.2+0.4r_{4,A} \\
   \end{aligned}
   $$
   
   Desde 4 podemos saltar directamente a $A$, a  $3$ y a $6$. Tenemos que:
   
   $$
   \begin{aligned}
       r_{4,A}&= p_{4,A}\cdot 1+ p_{4,3}\cdot r_{3,A}+p_{4,6}\cdot \cancelto{0}{r_{6,A}} \\
       &= 0.1+0.5r_{3,A} \\
   \end{aligned}
   $$
   
   Despejamos en la primera equación:
   
   $$
   \begin{aligned}
       r_{3,A}=0.2+0.4r_{4,A}&\implies r_{3,A}=0.2+0.4\cdot (0.1+0.5r_{3,A})\implies r_{3,A}=0.2+0.04+0.2r_{3,A}\\
       &\implies r_{3,A}-0.2r_{3,A}=0.24\implies 0.8r_{3,A}=0.24\\
       &\implies r_{3,A}=0.3 \\
   \end{aligned}
   $$

c) Sea $C=A\cup \{5,6\}.$ Calcula el **tiempo medio** (número esperado de pasos) hasta que la cadena alcance $C$, empezando en el estado 3.

   Consideramos ahora: 
   
   $$
   \tau_{3,C}=\mathbb{E}[\text{Tiempo hasta visitar $C$}|X_0=3]\text{ y }\tau_{4,C}=\mathbb{E}[\text{Tiempo hasta visitar $C$}|X_0=4]
   $$

   Como desde 3 podemos saltar directamente a 4 o a $C$, tenemos que:
    
   $$
   \tau_{3,C}=1+p_{3,4}\cdot \tau_{4,C}=1+0.4\tau_{4,C}
   $$

   Y como desde 4 podemos saltar directamente a 3 o a $C$, tenemos que: 

   
   $$
   \tau_{4,C}=1+p_{4,3}\cdot \tau_{3,C}=1+0.5\tau_{3,C}
   $$
   
   Despejando la primera ecuación tenemos que:
   
   $$
   \begin{aligned}
       \tau_{3,C}=1+0.4\tau_{4,C}&\implies \tau_{3,C}=1+0.4\cdot (1+0.5\tau_{3,C})\implies \tau_{3,C}=1+0.4+0.2\tau_{3,C} \\
       &\implies \tau_{3,C}-0.2\tau_{3,C}=1.4\implies 0.8\tau_{3,C}=1.4  \\
       &\implies \tau_{3,C}=1.75  \\
   \end{aligned}
   $$

d) Suponiendo que la cadena está en la clase cerrada $B=\{5,6\}$, determina la **probabilidad límite de visita** a cada estado de $B$ (distribución estacionaria en $B$) y justifica por qué existe.

   La cadena es irreducible ya que corresponde a la clase cerrada $C_3$. Además, existe $P_{5,5}>0$ y $P_{6,6}>0$, por lo que todos los estados tienen periodo 1.

   Al ser la cadena irreducible y aperiódica, tiene una distribución límite $\pi$, la cual es también una distribución estacionaria. En particular, podemos determinar $\pi$ resolviendo:

   
   $$
   \begin{cases}
       \pi=\pi\cdot P\\
       \displaystyle\sum_{i=1}^{n} \pi_i=1
   \end{cases}
   $$
   
   Esto nos lleva al sistema de ecuaciones:
   
   $$
   \begin{cases}
       \pi_5=0.6\pi_5+0.2\pi_6\\
       \pi_6=0.4\pi_5+0.8\pi_6\\
       \pi_5+\pi_6=1
   \end{cases}
   $$

   Resolvemos

   
   $$
   \begin{aligned}
       \pi_5=1-\pi_6&\rightarrow \pi_6=0.4\cdot (1-\pi_6)+0.8\pi_6\rightarrow \pi_6=0.4-0.4\pi_6+0.8\pi_6\\
       &\rightarrow \pi_6=0.4+0.4\pi_6\rightarrow \pi_6-0.4\pi_6=0.4\rightarrow 0.6\pi_6=0.4\\
       &\rightarrow \pi_6=\dfrac{2}{3}\implies \pi_5=1-\pi_6=\dfrac{1}{3}
   \end{aligned}
   $$
   
   Obtenemos finalmente: $$\pi_5=\dfrac{1}{3},\pi_6=\dfrac{2}{3}$$
   
# Problema 3 #

En un call center, llegan llamadas de dos tipos:

- Tipo A: proceso de Poisson con tasa $\lambda_A=4$ por hora.
- Tipo B: proceso de Poisson con tasa $\lambda_{B}=6$ por hora.

Ambos procesos son independientes. El call center abre a las 9:00.

a) Probabilidad de que en los **primeros 10 minutos** no llegue ninguna llamada.

   Consideramos los procesos:

   - $(N_t^A)_{t\in [0,\infty)}$, donde $N_t^A\sim \mathrm{Poisson}(\lambda_A=4)$
   - $(N_t^B)_{t\in [0,\infty)}$, donde $N_t^B\sim \mathrm{Poisson}(\lambda_B=6)$ 
   - $(N_t^T)_{t\in [0,\infty)}$, donde $N_t^T=N_t^A+N_t^B\sim \mathrm{Poisson}(\lambda_T=\lambda_A+\lambda_B=10)$ 

   Tenemos que calcular: $$\mathbb{P}(N_{\frac{1}{6} }^T=0).$$Sabemos que: $$N_{\frac{1}{6} }^T\sim \mathrm{Poisson}\left(\lambda_T\cdot \dfrac{1}{6}=\dfrac{5}{3}\right).$$ Por lo tanto: $$\mathbb{P}(N_{\frac{1}{6} }^T=0)=e^{-\frac{5}{3} } \cdot \dfrac{\left( \frac{5}{3}  \right)^0}{0!}=e^{-\frac{5}{3} }\approx 0.1889$$

b) Probabilidad de que entre 9:00 y 9:30 lleguen **exactamente 3 llamadas en total** y **exactamente 1 sea tipo A.**

   Tenemos que calcular: 
   $$
   \begin{aligned}
   \mathbb{P}((N_{\frac{1}{2}}^T-N_0^T=3)\cap (N_{\frac{1}{2}^A}-N_{0}^A=1))&=\mathbb{P}(N_{\frac{1}{2} }^T=3)\cdot \mathbb{P}(N_{\frac{1}{2}}^A=1)\\
   &=\left( e^{-5} \cdot \dfrac{5^3}{3!}  \right)\cdot \left( e^{-2} \cdot \dfrac{2^1}{1!} \right)\approx 0.038
   \end{aligned}
   $$
   
c) Sabiendo que entre 10:00 y 11:00 llegaron **8 llamadas en total**, calcula la probabilidad de que **al menos 5** fuesen de tipo B.

d) Probabilidad de que la **primera llamada total** sea de tipo B y ocurra **antes de 6 minutos** desde la 9:00.
